[package]
name = "kovi"
version = "0.5.0-rc1"
edition = "2021"
description = "A OneBot V11 bot plugin framework"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]
repository = "https://github.com/Threkork/Kovi"
readme = "README_Cargo.md"
documentation = "https://www.threkork.me/kovi-doc/"

[lib]
name = "kovi"
path = "src/lib.rs"

[dependencies]
toml = { version = "0.8" }
chrono = { version = "0.4", optional = true }
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
websocket-lite = "0.5.2"
log = "0.4"
anstyle = "1.0.8"
kovi-macros = "0.1.0"
regex = "1.10.6"
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
env_logger = { version = "0.11.5", default-features = false, features = [
    "auto-color",
    "color",
], optional = true }
colored = "2.1"


[features]
logger = ["env_logger", "chrono"]
