[package]
name = "kovi"
version = "0.5.0"
edition = "2021"
description = "A OneBot V11 bot plugin framework"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]
repository = "https://github.com/Threkork/Kovi"
readme = "README_Cargo.md"
documentation = "https://threkork.github.io/kovi-doc/"

[lib]
name = "kovi"
path = "src/lib.rs"

[dependencies]
chrono = { version = "0.4", optional = true }
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
log = "0.4"
anstyle = "1.0.8"
kovi-macros = "0.2.0"
regex = "1.10.6"
env_logger = { version = "0.11.5", default-features = false, features = [
    "auto-color",
    "color",
], optional = true }
tokio = { version = "1.39.3", features = ["full"] }
tokio-tungstenite = "0.23"
futures-util = "0.3"
reqwest = { version = "0.12", features = ["blocking"] }


[features]
logger = ["env_logger", "chrono"]
