[package]
name = "kovi"
version = "0.4.0"
edition = "2021"
description = "A OneBot V11 bot plugin framework"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]
repository = "https://github.com/Threkork/Kovi"
readme = "README_Cargo.md"
documentation = "https://www.threkork.me/kovi-doc/"

[lib]
name = "kovi"
path = "src/lib.rs"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
websocket-lite = "0.5.2"
env_logger = { version = "0.11.5", default-features = false, features = [
    "auto-color",
    "color",
] }
chrono = "0.4"
log = "0.4"
anstyle = "1.0.8"
kovi-macros = "0.1.0"
regex = "1.10.6"
