[package]
name = "kovi"
version = "0.2.0-rc1"
edition = "2021"
description = "A fast and lightweight OneBot V11 bot plugin framework"
license = "MPL-2.0"
authors = ["Threkork <threkork@hotmail.com>"]
repository = "https://github.com/Threkork/Kovi"
readme = "README_Cargo.md"

[dependencies]
dialoguer = { version = "0.11.0", features = ["fuzzy-select"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
websocket-lite = "0.5.2"
