---
name: Bug 反馈
description: 报告可能的 Kovi 异常行为
title: "[BUG] "
labels: potential bug
body:
  - type: markdown
    attributes:
      value: |
        欢迎来到 Kovi 的 Issue Tracker！请填写以下表格来提交 Bug。
        在提交新的 Bug 反馈前，请确保您：
        * 已经搜索了现有的 issues，并且没有找到可以解决您问题的方法
        * 不与现有的某一 issue 重复

  - type: input
    id: system-version
    attributes:
      label: 系统信息
      description: 运行 Kovi 的系统信息
      placeholder: Windows 10 Pro Workstation 22H2
    validations:
      required: true
  - type: input
    id: napcat-version
    attributes:
      label: Kovi 版本
      description: 可在 Cargo.toml 中找到
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: onebot-server-version
    attributes:
      label: OneBot 服务端
      description: 连接至 Kovi 的服务端版本信息
      placeholder: Napcat 2.5.0
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 发生了什么?
      description: 填写你认为的 Kovi 的不正常行为
    validations:
      required: true
  - type: textarea
    id: how-reproduce
    attributes:
      label: 如何复现
      description: 填写应当如何操作才能触发这个不正常行为
      placeholder: |
        1. xxx
        2. xxx
        3. xxx
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: 期望的结果?
      description: 填写你认为 Kovi 应当执行的正常行为
    validations:
      required: true
  - type: textarea
    id: kovi-log
    attributes:
      label: kovi 运行日志
      description: 粘贴相关日志内容到此处，通过从 kovi.conf.json 中打开 debug 模式获取更详细的日志
      render: shell
    validations:
      required: true

  - type: input
    id: any
    attributes:
      label: 你想填写的其它内容
      description: 填写其它想填写的内容
